### ISSUE TITLE
verifying the correctness of the on-chip network

### ISSUE THREAD

**Issue by Elena32061** [taichi-ishitani/tnoc#60]
Hello, I would like to ask the idea of ​​verifying the correctness of the on-chip network

**Comment by taichi-ishitani** [comment]
Hi @Elena32061 ,

Thank you for your asking this question and sorry for delay reply.

For TNoC project, I've introduced packet monitors and scoreboard checkers to check whether or not a router sends a packet to the correct destination. That is:

Env:

* put tx packet monitors to each tx packet ports of a router
* put rx packet monitors and scoreborad checkers to each rx packet ports of a router

How to work:

1. tx packet monitor caputures tx packets and send them to the expectation model
2. expectation model calcurates the expected destination of the given tx packet and send it to the scoreboard checker
3. rx packet monitor caputures rx packets and send them to the scoreboard checker
4. scoreboard checker compares rx packet given from rx packet monitor and tx packet given from the expection model

**Comment by Elena32061** [comment]
Thank you！


-----原始邮件-----
发件人:"Taichi Ishitani" ***@***.***>
发送时间:2022-09-17 22:19:46 (星期六)
收件人: taichi-ishitani/tnoc ***@***.***>
抄送: Elena ***@***.***>, Mention ***@***.***>
主题: Re: [taichi-ishitani/tnoc] verifying the correctness of the on-chip network (Issue #60)



Hi @Elena32061 ,

Thank you for your asking this question and sorry for delay reply.

For TNoC project, I've introduced packet monitors and scoreboard checkers to check whether or not a router sends a packet to the correct destination. That is:

Env:

put tx packet monitors to each tx packet ports of a router
put rx packet monitors and scoreborad checkers to each rx packet ports of a router

How to work:

tx packet monitor caputures tx packets and send them to the expectation model
expectation model calcurates the expected destination of the given tx packet and send it to the scoreboard checker
rx packet monitor caputures rx packets and send them to the scoreboard checker
scoreboard checker compares rx packet given from rx packet monitor and tx packet given from the expection model

**Comment by taichi-ishitani** [comment]
@Elena32061 ,
Can you close this issue if you have no further topics?
